#This is the template for What2Log Logs entries

# Meta data about this w2l entry
title = "" #Name of the log (i.e. User Logon)
W2L_schema = 1
author = "" #Your name
credits = [ "" ] #Any special callouts
release.version = "Ash"
release.date = 2022-04-27 #Todays date
tags = [ "" ] #Tags by which people can group pages

# About this log type
suggested_log_level = "" #Minimum, Ideal, Extreme, or Special Case
source.os = [ "" ]  #Applicable OS (i.e Windows 10 Pro) #app.os if application logs
source.service = "" #Service that generates log
source.log = "" #Log file or channel
default_enabled = true #true or false
collect_reason = """\

  """

# Additional References Go Here
references = [
  "blah",
  "blah2"
]

# Compliance & framework information

# Format is level and reference under the header [compliance.name]
# Only include relevant frameworks
[compliance.XXXX]
level = " " # Compliance requirement
reference = "URL here" # Reference for compliance

[compliance.YYYY]
level = " " # Compliance requirement
reference = "URL here" # Reference for compliance
# repeat as needed

# Log Pile
#Completely delete any section there is no code for
[log_pile]
language = "" #Language for Log Pile
view_logs = """ """ #How to view log
check_status = """ """ #How to check if log is enabled
enable_logging = """ """ #How to enable log
disable_logging = """ """ #How to disable log


# Enable via GUI
[[GUI.enable]]
img = "link to img 1"
txt = "text for step1 here"

[[GUI.enable]]
img = "link to img 2"
txt = "text for step 2 here"

# repeat as needed


# Enable via CLI
[[CLI.enable]]
img = " "
txt = " "

# repeat as needed


# View via GUI
[[GUI.view]]
img = " "
txt = " "

# repeat as needed


# View via CLI
# The first instance should be how to view via Get-WinEvent
[[CLI.view]]
img = " "
txt = ' '

# This isntance should be how to view via wevtutil
[[CLI.view]]
img = " "
txt = ' '

# repeat as needed
