#This is the template for What2Log Tools entries

# Meta data about this App entry
title = "Sysmon"
author = "Flynn Weeks"
credits = []
release.date = 2022-01-28
release.version = 0.1

# About this app
operating_system = ["Windows 10"]
default_installed = false #True or false only

#Installation Info (install info is optional, some tools are part of base os)
[[app.install]]
txt = """
Sysmon is a very useful Windows tool that can provide a few extra and more in \
depth logs. To install, visit https://docs.microsoft.com/en-us/sysinternals/ to \
get the newest version of Sysinternals.
"""

[[app.install]]
txt = """
This will download a zip file. Unzip the contents to a location of your \
choosing. Next, cd to the location that you unzipped the file to.
"""
img = "/Sysmon/CD.png"

[[app.install]]
txt = """
To install Sysmon, enter the command ```sysmon64.exe -accepteula -i``` . \
This command accepts the EULA information and installs sysmon onto your machine. \
If you are running a 32 bit system, omit the 64 in sysmon.exe.
"""
img = "/Sysmon/Install.png"

#continue as necessary

# App Info
[[app.info]]
txt = """
Sysmon logs can be viewed in the event viewer, just like normal windows logs. \
To view the sysmon log file, navigate the sysmon folder in event viewer, \
which can be found under the Windows folder.
"""
img = "/Sysmon/WEV.png"

[[app.info]]
txt = """
Under the sysmon folder, there is a operational log; this log file holds the \
logs generated by Sysmon.
"""
img = "/Sysmon/Operational.png"
#continue as necessary
