#This is the template for What2Log Tools entries

# Meta data about this App entry
title = "Windows PowerShell"
author = "Flynn Weeks"
credits = []
release.date = 2022-01-31
release.version = "Ash"

# About this app
operating_system = ["Windows 10"]
default_installed = true #True or false only

#Installation Info (install info is optional, some tools are part of base os)
#continue as necessary

# App Info
[[app.info]]
txt = """
The Windows 10 logs can be viewed either in the Command Prompt or in the \
PowerShell and there is no difference in the commands used. PowerShell, \
however, allows for a script to be written in order to automate the log process. \
To navigate to PowerShell, type powershell in the start menu. To enter the \
correct PowerShell app, the Windows PowerShell (highlighted in red) should be selected.
"""
img = "/Win10Powershell/Start.png"

[[app.info]]
txt = """
Much like the Command Prompt, PowerShell should be entered as an administrator \
and there are two ways to do so. The first is to click on number 1 (shown below) \
or right click on number 2 and select “run as administrator”. If the column on \
the right is not shown on your machine, simply use number 2.
"""
img = "/Win10Powershell/StartAsAdmin.png"

[[app.info]]
txt = """
Upon launching PowerShell as an administrator as an administrator, a popup may \
appear stating “Do you want to allow this app to make changes to your device?”. \
If prompted with this popup, click yes to continue.
"""
img = "/Win10Powershell/AllowAccess.png"

[[app.info]]
txt = """
Upon opening, Powershell displays this screen, which does not display \
much information to the user.
"""
img = "/Win10Powershell/CLI1.png"

[[app.info]]
txt = """
In order to navigate to the correct location for the log files, enter the \
command ```cd C:\WINDOWS\system32```
"""
img = "/Win10Powershell/CLI2.png"


[[app.info]]
txt = """
Windows PowerShell should be launched as an administrator in order to view logs \
as the location of the logs requires administrator access. If the PowerShell is \
launched without permissions, the output will not actually give the user \
any information.
"""
img = "/Win10Powershell/CLI3.png"



#continue as necessary
