#This is the template for What2Log Tools entries

# Meta data about this App entry
title = "Windows Command Prompt"
author = "Flynn Weeks"
credits = []
release.date = 2022-01-28
release.version = "Ash"

# About this app
operating_system = ["Windows 10"]
default_installed = true #True or false only

#Installation Info (install info is optional, some tools are part of base os)
#continue as necessary

# App Info
[[app.info]]
txt = """
The Windows command prompt allows for a straightforward way to view and filter \
logs without a graphic user interface. To navigate to the command prompt, open \
the start menu and search for “command” or “cmd”.
"""
img = "/Win10CLI/Start.png"

[[app.info]]
txt = """
It is recommended to enter the command prompt as an administrator to ensure \
that you have complete access to the system and all the logs. There are 2 ways \
to do this from the start menu. Clicking number 1 (pictured below) or right \
clicking number 2 and selecting “Run  as administrator”. If the column on the \
right is not shown on your machine, simply use number 2 Launching command prompt \
as an administrator creates what is known as an elevated command prompt.
"""
img = "/Win10CLI/RunAsAdmin.png"

[[app.info]]
txt = """
Upon launching Command Prompt as an administrator as an administrator, a popup \
may appear stating “Do you want to allow this app to make changes to your device?”. \
If prompted with this popup, click yes to continue to allow command prompt to open.
"""
img = "/Win10CLI/MakeChanges.png"

[[app.info]]
txt = """
Upon opening, the command prompt displays this screen, which does not display \
much information to the user.
"""
img = "/Win10CLI/CLI1.png"

[[app.info]]
txt = '''
First, for logging purposes, a user should ensure they are located in the right 
directory by entering the command ```cd C:\WINDOWS\system32``` If you are not
already in the correct folder, the command prompt will move you there and the
command line will now begin with **C:\WINDOWS\system32>**
'''
img = "/Win10CLI/CLI2.png"


[[app.info]]
txt = """
The Command Prompt should be run as an administrator because the files that \
hold the logs require administrator access. If the command prompt is run without \
administrator access, the return of the commands will not give a user an information.
"""
img = "/Win10CLI/CLI3.png"



#continue as necessary
